[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100

[tool.coverage.run]
source = [
    "fme_packager",
    "tests",
]
omit = [
    "*/tests/fixtures/**",
    "*/venv/**",
]
